Adding an option to add own handlers for routing (#36)
brainhubeu/hadron pull request #38
Opened 2018-07-05 14:12 UTC by marekbrainhub

This adds an event emitter inside the routing which allows for differently serializing the request and response objects.

2018-07-09 08:15 UTC, damian66 approved these changes

2018-07-10 11:00 UTC, szymonbrainhub requested changes
Could You add a test case, to check if this event is triggered with proper arguments? ~~Also please add link to PR with changes in documentation .~~ <- Done

2018-07-10 11:00 UTC, szymonbrainhub commented on packages/hadron-express/src/hadronToExpress.ts
> +          .then((cb) => {
Type would be usefull. Also let's try to avoid abbreviation of variables name (`cb`). It reduces readability without any real benefits.

2018-07-12 15:38 UTC, szymonbrainhub approved these changes

2018-07-12 15:38 UTC, merged